export const fileTypes = {
  media: [
    'mp3',
    'amr',
    'aac',
    'aif',
    'aifc',
    'aiff',
    'ogg',
    'wma',
    'flac',
    'ape',
    'wax',
    'midi',
    'mp4a',
    'weba',
    'ra',
    'ram',
    'rmp',
    'm3u',
    'wav',
    'soundcloud',
    'avi',
    'mp4',
    'mkv',
    'wmv',
    'vimeo',
    'youtube',
  ],
  text: ['xls', 'xlsx', 'doc', 'docx', 'rtf', 'txt', 'ppt', 'pptx', 'pps'],
  pdf: ['pdf'],
  archive: ['zip', 'cab', 'tar', 'tgz', 'gz', 'rar'],
  image: ['png', 'gif', 'bmp', 'tiff', 'jpg', 'jpeg'],
  link: ['htm', 'html'],
}
